sudo: required
services:
  - docker

before_install:
  - docker build -t ajaybojedla/currency-exchange-service .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ajaybojedla/currency-exchange-service